### ISSUE TITLE
Does not work in Ansible 1.9 and 2.0

### ISSUE THREAD

**Issue by joshunger** [lorin/ansible-docker-connection#3]
I'm getting this error -

`TypeError: exec_command() got an unexpected keyword argument 'become_user'`

I'm currently running `ansible-playbook 2.0.0`
